name: vainfo 
base: core20 
version: '0.1' 
summary: snap package including libdrm, libva and libva-utils
description: |
  single snap package including libdrm and libva as library and libva-utils as application.
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
architectures:
  - build-on: amd64
    run-on: amd64

parts:
  debs:
    plugin: nil
    build-packages:
      - cmake
      - meson
      - pkg-config
      - libpciaccess-dev
      - xutils-dev
      - valgrind
      - xsltproc
      - libx11-dev
      - python3-docutils
      - libwayland-dev 
      - libxext-dev
      - libxfixes-dev
      - libset-scalar-perl
      - perl
      - libgl1-mesa-dri
      - libgl1-mesa-dev
      - libelf-dev
      - libwayland-bin
      - doxygen
      - libva-dev

  vainfo:
    after: [ debs ]
    source: https://github.com/intel/libva-utils/archive/refs/tags/2.10.0.tar.gz
    plugin: meson
    meson-parameters:
      - --prefix=/usr
    stage-packages:
      - libwayland-client0
      - libxext6
      - libxfixes3
    build-snaps:
      - libva-test
    stage-snaps:
      - libva-test
    organize:
      vainfo: usr/bin/
      
apps:
  vainfo:
    command: usr/bin/vainfo
    environment: 
      LIBVA_DRIVER_NAME: iHD
      PATH: $SNAP/usr/local/bin:$PATH
      LIBVA_DRIVERS_PATH: $SNAP/usr/lib/x86_64-linux-gnu/dri

